version: "3.8"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        ports:
            - 9200:9200
        memory: 4096m

    kibana:
        image: docker.elastic.co/kibana/kibana:8.16.1
        environment:
            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        ports:
            - 5601:5601
